sudo: required
cache: pip
language: python
env:
  global:
    - secure: "O3DZe/AHLQBab/INKWQ2EdBINifxvT1ctJuNyB7i8hvILHbfswqMZTuaz7RQfTOhb+nyI9f+z2hIqJpNGoHfvmnFkrUegRpAPDhmSnPafCwVgymHdTX1//oGQ04LjQVCRPYzTiqmTLfQbyZnR2sloBkg20TE/0sDVi9EBsYeBH9uzvnlIHv1ExRgZFJJk2pjPegF8f5xHJl+kapTw4a5g2ZwqAcqH/UFebX1B3uHBCroa4C4DSXT/WOnIKW14pCK85lz8nqb0YODwpsSQeU2hWwQ9F9DrdMoW5hggFae2qD1FA0tnCtWlrr54xqcQkagUsR5475sp2Pb8BZE6RVBlPeKj+qpsxCedmF0dq0g901KqF4dPDHVS7XD7KB4/aPr7KFOu9HDo7rRn995FJu9KzI2RoTicXeyjcSGeeHNxZ5X87Ah3iWgn2ZU6aK1jgCRf3QNu6EGPZH90u8PrXz3XNWI8g3JiwVcsoXMSY/LfiVLnVJcmdK/VJiaOBP7pUqc54NkPNb9wsHXpJFQY6j9I3etdzShRNGntXg9obe6AgfJNlHAiL7Mv6jGgcpgegtLOs44FuO9ci49YROAsTPEEiMpGH9o0QZ2iM8yEFEidQSBlFbfJvsoYiIHjZliI2DHJMUfTcQ5aFXrF4Y2d4xpt8Le9VVAFF7glEs62CaHK5E="
    - secure: "isO5P14Rs5bVCD3IQqc/68ERAp6l8ZgND6iDR0n+ej3jk9WXfGaRJeiJTGRTIC3HKqu6pwZvFxgVbhgRSr42oaBlEkoVenKQSItPBXsAaDqfpCkO08di+QemGN6oOzqmzMO0V1Vt/920hYv+AVZ8QMEWl3keRioMV1SknvPaNiINHVxxQFJorzqBfQdulT3ksd2c1JS42sikqaUDOyOpgsRjh0OxTWFZ3VPKCCySlbFId2aQ76N16++Ho6qmfVOe3BKZeAJvTtDFb/skdDoINIVNL69172z34Kf3Cmh4aQEUjhCDgMxOOE1RVld6T+oQWKeb6rpTLZowWdVj7fFsN4VXpK5Yrh8LtZu6aAWzjKNAxrcd4tZZOsUebnSnbc2tCt2qewbk1aITVzFrmOoA4lkkCDOGakialx6zA2ji/QZBUQM5idGjI5qIPOwyxhotTNIw+wX+/6v+kHNaOqDJFUaxw6RbbVABpyfuT7vVK1JDxps8JHqTaudovEc7Q3A/wLxtgjH/OSIp96nagVqOrAzUvDnU9RTEOWe7yVnslHP23V8vebIZYyFBGnS4CKVxEMqIY0fjhg6nWUFYuBFDda+UzRkyvEmCSeEOEeYQ8zt6zXkFgYyDP8Xehr05yw4n7hp95sbUX0UG9sVPGdC4RFh7fB5u2B8rofeq3Q9Zm78="
matrix:
  include:
      - name: "Galaxy release_17.05 build"
        env: GALAXY_BRANCH=release_17.05
      - name: "Galaxy release_18.01 build"
        env: GALAXY_BRANCH=release_18.01
      - name: "Galaxy release_18.05 build"
        env: GALAXY_BRANCH=release_18.05
      - name: "Galaxy dev build"
        env: GALAXY_BRANCH=dev
  allow_failures:
      - name: "Galaxy dev build"
install:
    - pip install -r requirements.txt
script:
    - planemo lint
    - planemo test --conda_auto_install --conda_auto_init --conda_ensure_channels bioconda --galaxy_branch $GALAXY_BRANCH --no_cache_galaxy
after_success:
    - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then planemo shed_update --check_diff --shed_target toolshed --shed_email $SHED_EMAIL --shed_password $SHED_PASSWORD; fi
notifications:
    email:
        recipients:
            - $SHED_EMAIL
    on_success: never
